/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seproject;

import java.io.File;
import javax.swing.JOptionPane;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.write.Label;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;

/**
 *
 * @author MAHE
 */
public class CHANGEPASSWORD extends javax.swing.JFrame {
    int i;
    String b;
public CHANGEPASSWORD(int j,String q) {
    i=j;
    b=q;
        initComponents();       
    }

    public CHANGEPASSWORD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        npwd = new javax.swing.JTextField();
        cpwd = new javax.swing.JTextField();
        opwd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seproject/235624ffcf6f868.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seproject/235624ffcf6f868.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHANGE PASSWORD");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(162, 40, 169, 26);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NEW PASSWORD");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(72, 179, 102, 20);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CONFIRM PASSWORD");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 210, 132, 20);

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(89, 283, 70, 30);

        jButton2.setText("Change Password");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 280, 150, 30);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ENTER OLD PASSWORD");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 150, 142, 20);
        getContentPane().add(npwd);
        npwd.setBounds(240, 180, 130, 20);
        getContentPane().add(cpwd);
        cpwd.setBounds(240, 210, 130, 20);
        getContentPane().add(opwd);
        opwd.setBounds(240, 150, 130, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\MAHE\\Desktop\\SEPROJECT\\src\\seproject\\235624ffcf6f868.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 160, 450, 200);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\MAHE\\Desktop\\SEPROJECT\\src\\seproject\\235624ffcf6f868.jpg")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 500, 240);

        setSize(new java.awt.Dimension(461, 404));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String op=opwd.getText();
String np=npwd.getText();
String cp=cpwd.getText();
      try{    
           File f=new File("C:\\Users\\MAHE\\Desktop\\SEPROJECT\\src\\seproject\\Users.xls");            
           Workbook wb= Workbook.getWorkbook(f);
           Sheet s=wb.getSheet(0);       
               Cell c=s.getCell(2,i);
               if(c.getContents().equals(op)==false){               
               JOptionPane.showMessageDialog(null,"Old password invalid");
               opwd.setText("");
            }
           else{ 
                   int uc=0,lc=0,nc=0,fl=0;
                   if(np.length()<8)  fl=1;
                   for(int x=0;x<np.length();x++){
                       char q=np.charAt(x);
                       if(Character.isDigit(q)) nc++;
                       else if(Character.isLowerCase(q)) lc++;
                       else if(Character.isUpperCase(q)) uc++;
                    }
                   if(fl==1||nc==0||lc==0||uc==0){
                       JOptionPane.showMessageDialog(null,"Enter valid password \n Password should be atleast 8 characters \n with atleast one uppercase letter,atleast one lowercase \n letter and atleast one digit");
                       cpwd.setText("");
                       npwd.setText(""); 
                   }
                   else
                   if(cp.equals(np)==false){
                       JOptionPane.showMessageDialog(null,"Passwords do not match");
                       cpwd.setText("");
                       npwd.setText("");
                   }
                   else{
                   Workbook w1=Workbook.getWorkbook(f);
        WritableWorkbook w=Workbook.createWorkbook(f,w1);
        WritableSheet ws=w.getSheet(0);
        Label l=new Label(2,i,cp);
        ws.addCell(l);
        w.write();
        w.close();
        wb.close();
        JOptionPane.showMessageDialog(null,"Password changed successfully \n Please login again");
        this.dispose();
        new loginpage().setVisible(true);
               }}
                   }
      catch(Exception e){
      }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();
try{
if(b.equals("publicuser"))
new publicuser(i).setVisible(true);
else if(b.equals("researcher"))
new researcher(i).setVisible(true);
else if(b.equals("ngo"))
new ngo(i).setVisible(true);
else if(b.equals("Government"))
new Government().setVisible(true);
else if(b.equals("dbm"))
new dbmanager().setVisible(true);
}
catch(Exception e){
    
}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CHANGEPASSWORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CHANGEPASSWORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CHANGEPASSWORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CHANGEPASSWORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CHANGEPASSWORD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cpwd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField npwd;
    private javax.swing.JTextField opwd;
    // End of variables declaration//GEN-END:variables
}
