/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seproject;

import java.io.File;
import javax.swing.JOptionPane;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.write.Label;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;

/**
 *
 * @author MAHE
 */
public class CreateAccount extends javax.swing.JFrame {

    /**
     * Creates new form CreatAccount
     */
    public CreateAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        state = new javax.swing.JComboBox();
        type = new javax.swing.JComboBox();
        npwd = new javax.swing.JPasswordField();
        cpwd = new javax.swing.JPasswordField();
        pin = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CREATE ACCOUNT");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 30, 220, 43);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ENTER NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 120, 110, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ENTER EMAIL-ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 200, 137, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ENTER PHONE NUMBER");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 240, 193, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ENTER PASSWORD");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 370, 153, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("USER TYPE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 320, 90, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ENTER SECURITY PIN");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 450, 177, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("STATE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(220, 280, 53, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CONFIRM PASSWORD");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(100, 410, 176, 30);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(350, 200, 193, 30);

        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        getContentPane().add(phone);
        phone.setBounds(350, 240, 193, 28);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(350, 120, 193, 28);

        state.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ANDAMAN AND NICOBAR ISLANDS", "ANDHRA PRADESH", "ARUNACHAL PRADESH", "ASSAM", "BIHAR", "CHANDIGARH", "CHHATTISGARH", "DADRA AND NAGAR HAVELI", "DAMAN AND DIU", "DELHI", "GOA", "GUJARAT", "HARYANA", "HIMACHAL PRADESH", "JAMMU AND KASHMIR", "JHARKHAND", "KARNATAKA", "KERALA", "LAKSHADWEEP ", "MADHYA PRADESH", "MAHARASHTRA", "MANIPUR", "MEGHALAYA", "MIZORAM", "NAGALAND", "ODISHA", "PUDUCHERRY", "PUNJAB", "RAJASTHAN", "SIKKIM", "TAMIL NADU", "TELANGANA", "TRIPURA", "UTTARAKHAND", "UTTAR PRADESH", "WEST BENGAL" }));
        getContentPane().add(state);
        state.setBounds(350, 280, 193, 30);

        type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PUBLIC USER", "NGO", "RESEARCHER" }));
        getContentPane().add(type);
        type.setBounds(350, 320, 193, 30);
        getContentPane().add(npwd);
        npwd.setBounds(350, 370, 193, 30);
        getContentPane().add(cpwd);
        cpwd.setBounds(350, 410, 193, 30);
        getContentPane().add(pin);
        pin.setBounds(350, 450, 193, 30);

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 530, 70, 30);

        jButton2.setText("CREATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(340, 530, 100, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ENTER USERNAME");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(120, 160, 150, 30);
        getContentPane().add(username);
        username.setBounds(350, 160, 193, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\MAHE\\Desktop\\SEPROJECT\\src\\seproject\\235624ffcf6f868.jpg")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 380, 680, 250);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\MAHE\\Desktop\\SEPROJECT\\src\\seproject\\235624ffcf6f868.jpg")); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 140, 680, 250);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\MAHE\\Desktop\\SEPROJECT\\src\\seproject\\235624ffcf6f868.jpg")); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 680, 250);

        setSize(new java.awt.Dimension(697, 670));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.dispose();
    new homepage().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         String np=npwd.getText();
        String cp=cpwd.getText();
        String sp=pin.getText();
        String us=username.getText();
        String ph=phone.getText();
        String em=email.getText();
        File f;
         try{          
           if(name.getText().equals(""))
               JOptionPane.showMessageDialog(null,"Enter valid name");
           else {
               int i,flag=0;       
           f=new File("C:\\Users\\MAHE\\Desktop\\SEPROJECT\\src\\seproject\\Users.xls");             
           Workbook wb= Workbook.getWorkbook(f);
           Sheet s=wb.getSheet(0);  
           for(i=1;i<s.getRows();i++){
               Cell c=s.getCell(1,i);
               if(c.getContents().equals(us)){
                   flag=1;
                   break;}}
           if(us.length()<5)
           {
               JOptionPane.showMessageDialog(null,"Enter valid username \n Username should be minimum 5 characters");
               username.setText("");
           }
                 else  if(flag==1){
               JOptionPane.showMessageDialog(null,"Username already taken \n Please choose a different one");
               username.setText("");
           }
           else{
               if(em.endsWith(".com")==false||em.endsWith("@.com")||em.indexOf("@")==-1||Character.isLetterOrDigit(em.charAt(0))==false){
                    JOptionPane.showMessageDialog(null,"Enter valid email id");
               email.setText(""); 
               }
               else{
                   int f2=0,nd=0;
                       if(ph.length()!=10)
                          f2=1;
                       for(int x=0;x<ph.length();x++){
                           char c=ph.charAt(x);
                           if(Character.isDigit(c))
                               nd++;
                           else
                               f2=1;
                       }
                       if(f2==1||nd!=10){
                           JOptionPane.showMessageDialog(null,"Enter valid phone number");
               phone.setText(""); 
                          }
                       else{
                           int uc=0,lc=0,nc=0,fl=0;
                   if(np.length()<8)  fl=1;
                   for(int x=0;x<np.length();x++){
                       char q=np.charAt(x);
                       if(Character.isDigit(q)) nc++;
                       else if(Character.isLowerCase(q)) lc++;
                       else if(Character.isUpperCase(q)) uc++;
                    }
                   if(fl==1||nc==0||lc==0||uc==0){
                       JOptionPane.showMessageDialog(null,"Enter valid password \n Password should be atleast 8 characters \n with atleast one uppercase letter,atleast one lowercase \n letter and atleast one digit");
                       cpwd.setText("");
                       npwd.setText(""); 
                   }
                   else{
                   if(cp.equals(np)==false){
                       JOptionPane.showMessageDialog(null,"Passwords do not match");
                       cpwd.setText("");
                       npwd.setText("");
                       }
                   else{
                       int f1=0,n=0;
                       if(sp.length()!=4)
                          fl=1;
                       for(int x=0;x<sp.length();x++){
                           char cd=sp.charAt(x);
                           if(Character.isDigit(cd))
                               n++;
                           else
                               fl=1;
                       }
                       if(fl==1||n!=4){
                           JOptionPane.showMessageDialog(null,"Enter valid pin \n Pin should be a 4 digit number");
               pin.setText("");}
                       else{
                           Workbook w1=Workbook.getWorkbook(f);
        WritableWorkbook w=Workbook.createWorkbook(f,w1);
        WritableSheet ws=w.getSheet(0);
        i=ws.getRows();
        Label l=new Label(0,i,name.getText());
        ws.addCell(l);
        l=new Label(1,i,username.getText());
        ws.addCell(l);
        l=new Label(2,i,cp);
        ws.addCell(l);
        l=new Label(3,i,sp);
        ws.addCell(l);
        l=new Label(4,i,phone.getText());
        ws.addCell(l);
        l=new Label(5,i,email.getText());
        ws.addCell(l);
        l=new Label(6,i,(String)state.getSelectedItem());
        ws.addCell(l); 
        l=new Label(7,i,(String)type.getSelectedItem());
        ws.addCell(l);
        w.write();
        w.close();
        wb.close();
        JOptionPane.showMessageDialog(null,"Account created successfully \n Please login again");
        this.dispose();
        new loginpage().setVisible(true);
                       }
                   }
               }}}
           }
         }}
         catch(Exception e){
             
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cpwd;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField npwd;
    private javax.swing.JTextField phone;
    private javax.swing.JPasswordField pin;
    private javax.swing.JComboBox state;
    private javax.swing.JComboBox type;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
