/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seproject;

import java.io.*;
import javax.swing.JOptionPane;
import jxl.Cell;
import jxl.CellType;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;
import jxl.write.Label;
import jxl.write.WritableCell;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
import jxl.write.WriteException;
public class forgotpassword extends javax.swing.JFrame {

    /**
     * Creates new form forgotpassword
     */
    public forgotpassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        npwd = new javax.swing.JTextField();
        pin = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        cpwd = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORGOT PASSWORD");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(162, 50, 167, 26);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ENTER USERNAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(61, 120, 113, 20);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ENTER SECURITY PIN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 160, 131, 20);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NEW PASSWORD");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 200, 102, 20);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(178, 235, 0, 0);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CONFIRM PASSWORD");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 240, 132, 20);

        npwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npwdActionPerformed(evt);
            }
        });
        getContentPane().add(npwd);
        npwd.setBounds(245, 197, 112, 20);

        pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinActionPerformed(evt);
            }
        });
        getContentPane().add(pin);
        pin.setBounds(245, 159, 112, 20);

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 305, 100, 23);

        jButton2.setText("CHANGE PASSWORD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 305, 170, 23);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(245, 121, 112, 20);

        cpwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cpwdFocusLost(evt);
            }
        });
        cpwd.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cpwdInputMethodTextChanged(evt);
            }
        });
        cpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpwdActionPerformed(evt);
            }
        });
        getContentPane().add(cpwd);
        cpwd.setBounds(245, 235, 112, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seproject/235624ffcf6f868.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 170, 460, 230);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seproject/235624ffcf6f868.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 460, 240);

        setSize(new java.awt.Dimension(475, 429));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void npwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_npwdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      String n=name.getText();
      String sp=pin.getText();
      String np=npwd.getText();
      String cp=cpwd.getText();
      try{
           int i,flag=0;        
           File f=new File("C:\\Users\\MAHE\\Desktop\\SEPROJECT\\src\\seproject\\Users.xls");            
           Workbook wb= Workbook.getWorkbook(f);
           Sheet s=wb.getSheet(0);       
           for(i=0;i<s.getRows();i++){
               Cell c=s.getCell(1,i);
               if(c.getContents().equals(n)){
                   flag=1;
                   break;
                }         
            }
           if(flag==0){
               JOptionPane.showMessageDialog(null,"Enter valid username");
               name.setText("");
            }
           else{
               Cell p=s.getCell(3,i);
               if(p.getContents().equals(sp)==false){ 
                    JOptionPane.showMessageDialog(null,"Enter valid security pin");
                    pin.setText("");          
                }
               else{
                   int uc=0,lc=0,nc=0,fl=0;
                   if(np.length()<8)  fl=1;
                   for(int x=0;x<np.length();x++){
                       char q=np.charAt(x);
                       if(Character.isDigit(q)) nc++;
                       else if(Character.isLowerCase(q)) lc++;
                       else if(Character.isUpperCase(q)) uc++;
                    }
                   if(fl==1||nc==0||lc==0||uc==0){
                       JOptionPane.showMessageDialog(null,"Enter valid password \n Password should be atleast 8 characters \n with atleast one uppercase letter,atleast one lowercase \n letter and atleast one digit");
                       cpwd.setText("");
                       npwd.setText(""); 
                   }
                   else
                   if(cp.equals(np)==false){
                       JOptionPane.showMessageDialog(null,"Passwords do not match");
                       cpwd.setText("");
                       npwd.setText("");
                   }
                   else{
                   Workbook w1=Workbook.getWorkbook(f);
        WritableWorkbook w=Workbook.createWorkbook(f,w1);
        WritableSheet ws=w.getSheet(0);
        Label l=new Label(2,i,cp);
        ws.addCell(l);
        w.write();
        w.close();
        wb.close();
        JOptionPane.showMessageDialog(null,"Password changed successfully \n Please login again");
        this.dispose();
        new loginpage().setVisible(true);
               }}
                   }}
      catch(Exception e){
      }
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();
new homepage().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void cpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpwdActionPerformed

    private void cpwdInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cpwdInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cpwdInputMethodTextChanged

    private void cpwdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpwdFocusLost
       // TODO add your handling code here:
    }//GEN-LAST:event_cpwdFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgotpassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField cpwd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField name;
    public javax.swing.JTextField npwd;
    public javax.swing.JPasswordField pin;
    // End of variables declaration//GEN-END:variables
}
